name: Create build Windows

env:
  itchio_channel: windows
  BuildName: Quantum Quartz ${{github.event.release.tag_name}}
  ReleaseBody: ${{github.event.release.body}}
  BuildTarget: StandaloneWindows64
on:
  release:
    types: [ published , edited ]

jobs:
  buildForWindows:
    name: Build for Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: false
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ env.BuildTarget }}
          restore-keys: Library-

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows
          buildName: ${{ env.BuildName }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BuildName }}
          path: build/StandaloneWindows
  discordMessage:
    needs: buildForWindows
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Send Discord message
        uses: appleboy/discord-action@master
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          message: The ${{ github.event_name }} event triggered first step.